import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from "@/app/src/components/navbar/Navbar";
import Footer from "@/app/src/components/footer/Footer";
import {ThemeContextProvider} from "@/app/src/context/ThemeContext";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeContextProvider>
          <div className={"container"}>
              <div className={"wrapper"}>
                  <Navbar/>
                  {children}
                  <Footer/>
              </div>
          </div>
      </ThemeContextProvider>
      </body>
    </html>
  )
}
